### ISSUE TITLE
How to integrate with GitLab

### ISSUE THREAD

**Issue by phillipj** [tazjin/kontemplate#75]
I would really appreciate some hints about integrating kontemplate in a GitLab CI pipeline. Since you already such a setup up-n-running, are you able to give a rough outline of what's needed?

**Comment by tazjin** [comment]
Yes, I'm planning to write a document for various suggested CI alternatives.

The way we've done it with Gitlab specifically is by having a specialised Gitlab CI runner for kontemplate only that runs in each cluster that we use as a deployment target. Actual builds happen with [this image](https://hub.docker.com/r/tazjin/kontemplate/) which contains kontemplate and pass.

Every build first runs a `kontemplate apply --dry-run` as part of a `check` phase and then `kontemplate apply` in all test clusters automatically, with a `manual` action required on production clusters.

**Comment by phillipj** [comment]
Thanks! Let me know if you need some help reviewing those docs and being a guinea pig running through them.

**Comment by phillipj** [comment]
Any progress on the documentation and/or new tricks you've found that has proven valuable while running `kontemplate` in a CI setting?

**Comment by tazjin** [comment]
I never actually got around to setting up docs for this. There's a demo repo somewhere on Gitlab, but I can't find it right now.

The source of kontemplate is moving to [git.tazj.in](https://git.tazj.in/tree/ops/kontemplate) and I'm closing the issues over here. Please email depot@tazj.in if you think this issue is still relevant!
